import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const prisma = new PrismaClient();

const solidityContracts = [
  { name: 'SimpleToken', fileName: 'SimpleToken.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/ERC20.sol";\n\ncontract SimpleToken is ERC20 {\n    address public owner;\n    uint256 public maxSupply;\n\n    constructor(uint256 _maxSupply) ERC20("SimpleToken", "STK") {\n        owner = msg.sender;\n        maxSupply = _maxSupply;\n        _mint(msg.sender, _maxSupply);\n    }\n\n    function mint(address to, uint256 amount) public {\n        require(msg.sender == owner, "Not owner");\n        require(totalSupply() + amount <= maxSupply, "Exceeds max supply");\n        _mint(to, amount);\n    }\n\n    function burn(uint256 amount) public {\n        _burn(msg.sender, amount);\n    }\n}`, version: '0.8.19', desc: 'Basic ERC20 token with minting and burning' },
  { name: 'VulnerableVault', fileName: 'VulnerableVault.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract VulnerableVault {\n    mapping(address => uint256) public balances;\n\n    function deposit() external payable {\n        balances[msg.sender] += msg.value;\n    }\n\n    function withdraw() external {\n        uint256 bal = balances[msg.sender];\n        require(bal > 0, "No balance");\n        (bool sent, ) = msg.sender.call{value: bal}("");\n        require(sent, "Transfer failed");\n        balances[msg.sender] = 0;\n    }\n\n    function getBalance() external view returns (uint256) {\n        return address(this).balance;\n    }\n}`, version: '0.8.19', desc: 'Vault contract with potential reentrancy vulnerability' },
  { name: 'NFTMarketplace', fileName: 'NFTMarketplace.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC721/IERC721.sol";\nimport "@openzeppelin/contracts/security/ReentrancyGuard.sol";\n\ncontract NFTMarketplace is ReentrancyGuard {\n    struct Listing {\n        address seller;\n        address nftContract;\n        uint256 tokenId;\n        uint256 price;\n        bool active;\n    }\n\n    mapping(uint256 => Listing) public listings;\n    uint256 public listingCount;\n    uint256 public platformFee = 250; // 2.5%\n\n    event Listed(uint256 listingId, address seller, uint256 price);\n    event Sold(uint256 listingId, address buyer, uint256 price);\n\n    function listNFT(address nftContract, uint256 tokenId, uint256 price) external {\n        require(price > 0, "Price must be > 0");\n        IERC721(nftContract).transferFrom(msg.sender, address(this), tokenId);\n        listings[listingCount] = Listing(msg.sender, nftContract, tokenId, price, true);\n        emit Listed(listingCount, msg.sender, price);\n        listingCount++;\n    }\n\n    function buyNFT(uint256 listingId) external payable nonReentrant {\n        Listing storage listing = listings[listingId];\n        require(listing.active, "Not active");\n        require(msg.value >= listing.price, "Insufficient payment");\n        listing.active = false;\n        uint256 fee = (listing.price * platformFee) / 10000;\n        payable(listing.seller).transfer(listing.price - fee);\n        IERC721(listing.nftContract).transferFrom(address(this), msg.sender, listing.tokenId);\n        emit Sold(listingId, msg.sender, listing.price);\n    }\n}`, version: '0.8.19', desc: 'NFT marketplace with listing and buying' },
  { name: 'StakingRewards', fileName: 'StakingRewards.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ncontract StakingRewards {\n    IERC20 public stakingToken;\n    IERC20 public rewardToken;\n    address public owner;\n    uint256 public rewardRate = 100;\n    uint256 public lastUpdateTime;\n    uint256 public rewardPerTokenStored;\n    uint256 public totalStaked;\n\n    mapping(address => uint256) public stakedBalance;\n    mapping(address => uint256) public rewards;\n    mapping(address => uint256) public userRewardPerTokenPaid;\n\n    constructor(address _stakingToken, address _rewardToken) {\n        stakingToken = IERC20(_stakingToken);\n        rewardToken = IERC20(_rewardToken);\n        owner = msg.sender;\n    }\n\n    function stake(uint256 amount) external {\n        require(amount > 0, "Cannot stake 0");\n        updateReward(msg.sender);\n        totalStaked += amount;\n        stakedBalance[msg.sender] += amount;\n        stakingToken.transferFrom(msg.sender, address(this), amount);\n    }\n\n    function withdraw(uint256 amount) external {\n        require(amount > 0, "Cannot withdraw 0");\n        updateReward(msg.sender);\n        totalStaked -= amount;\n        stakedBalance[msg.sender] -= amount;\n        stakingToken.transfer(msg.sender, amount);\n    }\n\n    function claimReward() external {\n        updateReward(msg.sender);\n        uint256 reward = rewards[msg.sender];\n        if (reward > 0) {\n            rewards[msg.sender] = 0;\n            rewardToken.transfer(msg.sender, reward);\n        }\n    }\n\n    function updateReward(address account) internal {\n        rewardPerTokenStored = rewardPerToken();\n        lastUpdateTime = block.timestamp;\n        rewards[account] = earned(account);\n        userRewardPerTokenPaid[account] = rewardPerTokenStored;\n    }\n\n    function rewardPerToken() public view returns (uint256) {\n        if (totalStaked == 0) return rewardPerTokenStored;\n        return rewardPerTokenStored + ((block.timestamp - lastUpdateTime) * rewardRate * 1e18) / totalStaked;\n    }\n\n    function earned(address account) public view returns (uint256) {\n        return (stakedBalance[account] * (rewardPerToken() - userRewardPerTokenPaid[account])) / 1e18 + rewards[account];\n    }\n}`, version: '0.8.19', desc: 'Staking contract with reward distribution' },
  { name: 'GovernorDAO', fileName: 'GovernorDAO.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract GovernorDAO {\n    struct Proposal {\n        uint256 id;\n        address proposer;\n        string description;\n        uint256 forVotes;\n        uint256 againstVotes;\n        uint256 deadline;\n        bool executed;\n        mapping(address => bool) hasVoted;\n    }\n\n    mapping(uint256 => Proposal) public proposals;\n    mapping(address => uint256) public votingPower;\n    uint256 public proposalCount;\n    uint256 public quorum = 1000;\n    uint256 public votingPeriod = 3 days;\n\n    function propose(string memory description) external returns (uint256) {\n        require(votingPower[msg.sender] > 0, "No voting power");\n        uint256 proposalId = proposalCount++;\n        Proposal storage p = proposals[proposalId];\n        p.id = proposalId;\n        p.proposer = msg.sender;\n        p.description = description;\n        p.deadline = block.timestamp + votingPeriod;\n        return proposalId;\n    }\n\n    function vote(uint256 proposalId, bool support) external {\n        Proposal storage p = proposals[proposalId];\n        require(block.timestamp < p.deadline, "Voting ended");\n        require(!p.hasVoted[msg.sender], "Already voted");\n        p.hasVoted[msg.sender] = true;\n        if (support) p.forVotes += votingPower[msg.sender];\n        else p.againstVotes += votingPower[msg.sender];\n    }\n}`, version: '0.8.19', desc: 'Simple governance DAO with proposal voting' },
  { name: 'DEXRouter', fileName: 'DEXRouter.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ncontract DEXRouter {\n    struct Pool {\n        address tokenA;\n        address tokenB;\n        uint256 reserveA;\n        uint256 reserveB;\n        uint256 totalLiquidity;\n        mapping(address => uint256) liquidity;\n    }\n\n    mapping(bytes32 => Pool) public pools;\n\n    function getPoolId(address tokenA, address tokenB) public pure returns (bytes32) {\n        return keccak256(abi.encodePacked(tokenA < tokenB ? tokenA : tokenB, tokenA < tokenB ? tokenB : tokenA));\n    }\n\n    function addLiquidity(address tokenA, address tokenB, uint256 amountA, uint256 amountB) external {\n        bytes32 poolId = getPoolId(tokenA, tokenB);\n        Pool storage pool = pools[poolId];\n        if (pool.tokenA == address(0)) {\n            pool.tokenA = tokenA < tokenB ? tokenA : tokenB;\n            pool.tokenB = tokenA < tokenB ? tokenB : tokenA;\n        }\n        IERC20(tokenA).transferFrom(msg.sender, address(this), amountA);\n        IERC20(tokenB).transferFrom(msg.sender, address(this), amountB);\n        uint256 liq = amountA + amountB;\n        pool.reserveA += amountA;\n        pool.reserveB += amountB;\n        pool.totalLiquidity += liq;\n        pool.liquidity[msg.sender] += liq;\n    }\n\n    function swap(address tokenIn, address tokenOut, uint256 amountIn) external {\n        bytes32 poolId = getPoolId(tokenIn, tokenOut);\n        Pool storage pool = pools[poolId];\n        require(pool.reserveA > 0 && pool.reserveB > 0, "No liquidity");\n        bool isAtoB = tokenIn == pool.tokenA;\n        uint256 reserveIn = isAtoB ? pool.reserveA : pool.reserveB;\n        uint256 reserveOut = isAtoB ? pool.reserveB : pool.reserveA;\n        uint256 amountOut = (amountIn * reserveOut) / (reserveIn + amountIn);\n        IERC20(tokenIn).transferFrom(msg.sender, address(this), amountIn);\n        IERC20(tokenOut).transfer(msg.sender, amountOut);\n        if (isAtoB) { pool.reserveA += amountIn; pool.reserveB -= amountOut; }\n        else { pool.reserveB += amountIn; pool.reserveA -= amountOut; }\n    }\n}`, version: '0.8.19', desc: 'Decentralized exchange router with AMM' },
  { name: 'MultiSigWallet', fileName: 'MultiSigWallet.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract MultiSigWallet {\n    address[] public owners;\n    uint256 public required;\n    uint256 public transactionCount;\n\n    struct Transaction {\n        address to;\n        uint256 value;\n        bytes data;\n        bool executed;\n        uint256 confirmations;\n    }\n\n    mapping(uint256 => Transaction) public transactions;\n    mapping(uint256 => mapping(address => bool)) public confirmations;\n    mapping(address => bool) public isOwner;\n\n    modifier onlyOwner() { require(isOwner[msg.sender], "Not owner"); _; }\n\n    constructor(address[] memory _owners, uint256 _required) {\n        require(_owners.length >= _required, "Invalid required");\n        for (uint i = 0; i < _owners.length; i++) {\n            isOwner[_owners[i]] = true;\n        }\n        owners = _owners;\n        required = _required;\n    }\n\n    function submitTransaction(address to, uint256 value, bytes memory data) public onlyOwner {\n        transactions[transactionCount] = Transaction(to, value, data, false, 0);\n        transactionCount++;\n    }\n\n    function confirmTransaction(uint256 txId) public onlyOwner {\n        require(!confirmations[txId][msg.sender], "Already confirmed");\n        confirmations[txId][msg.sender] = true;\n        transactions[txId].confirmations++;\n    }\n\n    function executeTransaction(uint256 txId) public onlyOwner {\n        Transaction storage txn = transactions[txId];\n        require(txn.confirmations >= required, "Not enough confirmations");\n        require(!txn.executed, "Already executed");\n        txn.executed = true;\n        (bool success, ) = txn.to.call{value: txn.value}(txn.data);\n        require(success, "Tx failed");\n    }\n\n    receive() external payable {}\n}`, version: '0.8.19', desc: 'Multi-signature wallet requiring multiple approvals' },
  { name: 'TokenVesting', fileName: 'TokenVesting.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ncontract TokenVesting {\n    struct VestingSchedule {\n        address beneficiary;\n        uint256 totalAmount;\n        uint256 released;\n        uint256 start;\n        uint256 cliff;\n        uint256 duration;\n        bool revocable;\n        bool revoked;\n    }\n\n    IERC20 public token;\n    address public owner;\n    mapping(bytes32 => VestingSchedule) public schedules;\n    uint256 public scheduleCount;\n\n    constructor(address _token) {\n        token = IERC20(_token);\n        owner = msg.sender;\n    }\n\n    function createSchedule(address beneficiary, uint256 amount, uint256 cliff, uint256 duration, bool revocable) external {\n        require(msg.sender == owner, "Not owner");\n        bytes32 id = keccak256(abi.encodePacked(beneficiary, scheduleCount));\n        schedules[id] = VestingSchedule(beneficiary, amount, 0, block.timestamp, cliff, duration, revocable, false);\n        token.transferFrom(msg.sender, address(this), amount);\n        scheduleCount++;\n    }\n\n    function release(bytes32 scheduleId) external {\n        VestingSchedule storage s = schedules[scheduleId];\n        require(msg.sender == s.beneficiary, "Not beneficiary");\n        uint256 vested = vestedAmount(scheduleId);\n        uint256 releasable = vested - s.released;\n        require(releasable > 0, "Nothing to release");\n        s.released += releasable;\n        token.transfer(s.beneficiary, releasable);\n    }\n\n    function vestedAmount(bytes32 scheduleId) public view returns (uint256) {\n        VestingSchedule storage s = schedules[scheduleId];\n        if (block.timestamp < s.start + s.cliff) return 0;\n        if (block.timestamp >= s.start + s.duration || s.revoked) return s.totalAmount;\n        return (s.totalAmount * (block.timestamp - s.start)) / s.duration;\n    }\n}`, version: '0.8.19', desc: 'Token vesting with cliff and linear release' },
  { name: 'FlashLoanProvider', fileName: 'FlashLoanProvider.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ninterface IFlashBorrower {\n    function onFlashLoan(address token, uint256 amount, uint256 fee, bytes calldata data) external;\n}\n\ncontract FlashLoanProvider {\n    uint256 public constant FEE_BPS = 9; // 0.09%\n    mapping(address => uint256) public poolBalance;\n    address public owner;\n\n    constructor() { owner = msg.sender; }\n\n    function deposit(address token, uint256 amount) external {\n        IERC20(token).transferFrom(msg.sender, address(this), amount);\n        poolBalance[token] += amount;\n    }\n\n    function flashLoan(address token, uint256 amount, bytes calldata data) external {\n        uint256 balanceBefore = IERC20(token).balanceOf(address(this));\n        require(balanceBefore >= amount, "Insufficient pool");\n        uint256 fee = (amount * FEE_BPS) / 10000;\n        IERC20(token).transfer(msg.sender, amount);\n        IFlashBorrower(msg.sender).onFlashLoan(token, amount, fee, data);\n        uint256 balanceAfter = IERC20(token).balanceOf(address(this));\n        require(balanceAfter >= balanceBefore + fee, "Loan not repaid");\n        poolBalance[token] = balanceAfter;\n    }\n}`, version: '0.8.19', desc: 'Flash loan provider with fee mechanism' },
  { name: 'Timelock', fileName: 'Timelock.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract Timelock {\n    address public admin;\n    uint256 public delay;\n    mapping(bytes32 => bool) public queuedTransactions;\n\n    event TransactionQueued(bytes32 txHash, address target, uint256 value, uint256 eta);\n    event TransactionExecuted(bytes32 txHash);\n\n    constructor(uint256 _delay) {\n        admin = msg.sender;\n        delay = _delay;\n    }\n\n    function queueTransaction(address target, uint256 value, bytes memory data, uint256 eta) public returns (bytes32) {\n        require(msg.sender == admin, "Not admin");\n        require(eta >= block.timestamp + delay, "ETA too soon");\n        bytes32 txHash = keccak256(abi.encode(target, value, data, eta));\n        queuedTransactions[txHash] = true;\n        emit TransactionQueued(txHash, target, value, eta);\n        return txHash;\n    }\n\n    function executeTransaction(address target, uint256 value, bytes memory data, uint256 eta) public payable {\n        require(msg.sender == admin, "Not admin");\n        bytes32 txHash = keccak256(abi.encode(target, value, data, eta));\n        require(queuedTransactions[txHash], "Not queued");\n        require(block.timestamp >= eta, "Too early");\n        queuedTransactions[txHash] = false;\n        (bool success, ) = target.call{value: value}(data);\n        require(success, "Tx failed");\n        emit TransactionExecuted(txHash);\n    }\n}`, version: '0.8.19', desc: 'Timelock controller for governance' },
  { name: 'PriceOracle', fileName: 'PriceOracle.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract PriceOracle {\n    struct PriceData {\n        uint256 price;\n        uint256 timestamp;\n        address reporter;\n    }\n\n    mapping(address => PriceData) public prices;\n    mapping(address => bool) public authorizedReporters;\n    address public owner;\n\n    constructor() { owner = msg.sender; authorizedReporters[msg.sender] = true; }\n\n    function setPrice(address token, uint256 price) external {\n        require(authorizedReporters[msg.sender], "Unauthorized");\n        prices[token] = PriceData(price, block.timestamp, msg.sender);\n    }\n\n    function getPrice(address token) external view returns (uint256 price, uint256 timestamp) {\n        PriceData storage data = prices[token];\n        require(data.timestamp > 0, "No price");\n        require(block.timestamp - data.timestamp < 1 hours, "Stale price");\n        return (data.price, data.timestamp);\n    }\n\n    function addReporter(address reporter) external {\n        require(msg.sender == owner, "Not owner");\n        authorizedReporters[reporter] = true;\n    }\n}`, version: '0.8.19', desc: 'Price oracle with authorized reporters' },
  { name: 'LendingPool', fileName: 'LendingPool.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ncontract LendingPool {\n    struct UserAccount {\n        uint256 deposited;\n        uint256 borrowed;\n        uint256 collateral;\n    }\n\n    IERC20 public token;\n    mapping(address => UserAccount) public accounts;\n    uint256 public totalDeposits;\n    uint256 public totalBorrows;\n    uint256 public collateralFactor = 150; // 150%\n    uint256 public interestRate = 5; // 5%\n\n    constructor(address _token) { token = IERC20(_token); }\n\n    function deposit(uint256 amount) external {\n        token.transferFrom(msg.sender, address(this), amount);\n        accounts[msg.sender].deposited += amount;\n        totalDeposits += amount;\n    }\n\n    function borrow(uint256 amount) external {\n        UserAccount storage account = accounts[msg.sender];\n        uint256 maxBorrow = (account.collateral * 100) / collateralFactor;\n        require(account.borrowed + amount <= maxBorrow, "Insufficient collateral");\n        account.borrowed += amount;\n        totalBorrows += amount;\n        token.transfer(msg.sender, amount);\n    }\n\n    function repay(uint256 amount) external {\n        token.transferFrom(msg.sender, address(this), amount);\n        accounts[msg.sender].borrowed -= amount;\n        totalBorrows -= amount;\n    }\n\n    function depositCollateral() external payable {\n        accounts[msg.sender].collateral += msg.value;\n    }\n}`, version: '0.8.19', desc: 'Simple lending pool with collateralized borrowing' },
  { name: 'ERC721Collection', fileName: 'ERC721Collection.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC721/ERC721.sol";\nimport "@openzeppelin/contracts/access/Ownable.sol";\n\ncontract ERC721Collection is ERC721, Ownable {\n    uint256 public totalMinted;\n    uint256 public maxSupply;\n    uint256 public mintPrice;\n    string private _baseTokenURI;\n    bool public saleActive;\n\n    constructor(string memory name, string memory symbol, uint256 _maxSupply, uint256 _mintPrice)\n        ERC721(name, symbol) Ownable(msg.sender) {\n        maxSupply = _maxSupply;\n        mintPrice = _mintPrice;\n    }\n\n    function mint(uint256 quantity) external payable {\n        require(saleActive, "Sale not active");\n        require(totalMinted + quantity <= maxSupply, "Exceeds max supply");\n        require(msg.value >= mintPrice * quantity, "Insufficient payment");\n        for (uint i = 0; i < quantity; i++) {\n            _safeMint(msg.sender, totalMinted);\n            totalMinted++;\n        }\n    }\n\n    function setBaseURI(string memory baseURI) external onlyOwner {\n        _baseTokenURI = baseURI;\n    }\n\n    function toggleSale() external onlyOwner {\n        saleActive = !saleActive;\n    }\n\n    function withdraw() external onlyOwner {\n        payable(owner()).transfer(address(this).balance);\n    }\n}`, version: '0.8.19', desc: 'ERC721 NFT collection with minting' },
  { name: 'BridgeContract', fileName: 'BridgeContract.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/IERC20.sol";\n\ncontract BridgeContract {\n    address public validator;\n    uint256 public nonce;\n    mapping(bytes32 => bool) public processedMessages;\n\n    event Deposit(address token, address sender, uint256 amount, uint256 destChainId, uint256 nonce);\n    event Withdrawal(address token, address recipient, uint256 amount, uint256 srcNonce);\n\n    constructor(address _validator) {\n        validator = _validator;\n    }\n\n    function deposit(address token, uint256 amount, uint256 destChainId) external {\n        IERC20(token).transferFrom(msg.sender, address(this), amount);\n        emit Deposit(token, msg.sender, amount, destChainId, nonce);\n        nonce++;\n    }\n\n    function withdraw(address token, address recipient, uint256 amount, uint256 srcNonce, bytes memory signature) external {\n        bytes32 messageHash = keccak256(abi.encodePacked(token, recipient, amount, srcNonce));\n        require(!processedMessages[messageHash], "Already processed");\n        require(recoverSigner(messageHash, signature) == validator, "Invalid signature");\n        processedMessages[messageHash] = true;\n        IERC20(token).transfer(recipient, amount);\n        emit Withdrawal(token, recipient, amount, srcNonce);\n    }\n\n    function recoverSigner(bytes32 hash, bytes memory sig) internal pure returns (address) {\n        bytes32 ethHash = keccak256(abi.encodePacked("\\x19Ethereum Signed Message:\\n32", hash));\n        (bytes32 r, bytes32 s, uint8 v) = splitSig(sig);\n        return ecrecover(ethHash, v, r, s);\n    }\n\n    function splitSig(bytes memory sig) internal pure returns (bytes32 r, bytes32 s, uint8 v) {\n        require(sig.length == 65, "Invalid sig length");\n        assembly { r := mload(add(sig, 32)) s := mload(add(sig, 64)) v := byte(0, mload(add(sig, 96))) }\n    }\n}`, version: '0.8.19', desc: 'Cross-chain bridge with validator signatures' },
  { name: 'AuctionHouse', fileName: 'AuctionHouse.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract AuctionHouse {\n    struct Auction {\n        address seller;\n        uint256 startPrice;\n        uint256 highestBid;\n        address highestBidder;\n        uint256 endTime;\n        bool ended;\n    }\n\n    mapping(uint256 => Auction) public auctions;\n    uint256 public auctionCount;\n    mapping(uint256 => mapping(address => uint256)) public pendingReturns;\n\n    function createAuction(uint256 startPrice, uint256 duration) external {\n        auctions[auctionCount] = Auction(msg.sender, startPrice, 0, address(0), block.timestamp + duration, false);\n        auctionCount++;\n    }\n\n    function bid(uint256 auctionId) external payable {\n        Auction storage a = auctions[auctionId];\n        require(block.timestamp < a.endTime, "Auction ended");\n        require(msg.value > a.highestBid && msg.value >= a.startPrice, "Bid too low");\n        if (a.highestBidder != address(0)) {\n            pendingReturns[auctionId][a.highestBidder] += a.highestBid;\n        }\n        a.highestBid = msg.value;\n        a.highestBidder = msg.sender;\n    }\n\n    function withdrawBid(uint256 auctionId) external {\n        uint256 amount = pendingReturns[auctionId][msg.sender];\n        require(amount > 0, "Nothing to withdraw");\n        pendingReturns[auctionId][msg.sender] = 0;\n        payable(msg.sender).transfer(amount);\n    }\n\n    function endAuction(uint256 auctionId) external {\n        Auction storage a = auctions[auctionId];\n        require(block.timestamp >= a.endTime, "Not ended yet");\n        require(!a.ended, "Already ended");\n        a.ended = true;\n        payable(a.seller).transfer(a.highestBid);\n    }\n}`, version: '0.8.19', desc: 'English auction with bid management' },
  { name: 'PaymentSplitter', fileName: 'PaymentSplitter.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract PaymentSplitter {\n    address[] public payees;\n    mapping(address => uint256) public shares;\n    mapping(address => uint256) public released;\n    uint256 public totalShares;\n    uint256 public totalReleased;\n\n    constructor(address[] memory _payees, uint256[] memory _shares) {\n        require(_payees.length == _shares.length, "Length mismatch");\n        for (uint i = 0; i < _payees.length; i++) {\n            payees.push(_payees[i]);\n            shares[_payees[i]] = _shares[i];\n            totalShares += _shares[i];\n        }\n    }\n\n    receive() external payable {}\n\n    function release(address payable account) public {\n        require(shares[account] > 0, "No shares");\n        uint256 totalReceived = address(this).balance + totalReleased;\n        uint256 payment = (totalReceived * shares[account]) / totalShares - released[account];\n        require(payment > 0, "Nothing due");\n        released[account] += payment;\n        totalReleased += payment;\n        account.transfer(payment);\n    }\n}`, version: '0.8.19', desc: 'Payment splitter for revenue sharing' },
  { name: 'Escrow', fileName: 'Escrow.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\ncontract Escrow {\n    struct Deal {\n        address buyer;\n        address seller;\n        uint256 amount;\n        bool buyerApproved;\n        bool sellerDelivered;\n        bool completed;\n        bool disputed;\n    }\n\n    mapping(uint256 => Deal) public deals;\n    uint256 public dealCount;\n    address public arbiter;\n\n    constructor(address _arbiter) { arbiter = _arbiter; }\n\n    function createDeal(address seller) external payable {\n        require(msg.value > 0, "Must send ETH");\n        deals[dealCount] = Deal(msg.sender, seller, msg.value, false, false, false, false);\n        dealCount++;\n    }\n\n    function confirmDelivery(uint256 dealId) external {\n        Deal storage d = deals[dealId];\n        require(msg.sender == d.seller, "Not seller");\n        d.sellerDelivered = true;\n    }\n\n    function approveRelease(uint256 dealId) external {\n        Deal storage d = deals[dealId];\n        require(msg.sender == d.buyer, "Not buyer");\n        require(d.sellerDelivered, "Not delivered");\n        d.buyerApproved = true;\n        d.completed = true;\n        payable(d.seller).transfer(d.amount);\n    }\n\n    function dispute(uint256 dealId) external {\n        Deal storage d = deals[dealId];\n        require(msg.sender == d.buyer || msg.sender == d.seller, "Not party");\n        d.disputed = true;\n    }\n\n    function resolveDispute(uint256 dealId, address winner) external {\n        require(msg.sender == arbiter, "Not arbiter");\n        Deal storage d = deals[dealId];\n        require(d.disputed, "Not disputed");\n        d.completed = true;\n        payable(winner).transfer(d.amount);\n    }\n}`, version: '0.8.19', desc: 'Escrow service with dispute resolution' },
  { name: 'TokenFactory', fileName: 'TokenFactory.sol', code: `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.19;\n\nimport "@openzeppelin/contracts/token/ERC20/ERC20.sol";\n\ncontract FactoryToken is ERC20 {\n    address public creator;\n    constructor(string memory name, string memory symbol, uint256 supply, address _creator)\n        ERC20(name, symbol) {\n        creator = _creator;\n        _mint(_creator, supply);\n    }\n}\n\ncontract TokenFactory {\n    address[] public deployedTokens;\n    mapping(address => address[]) public creatorTokens;\n\n    event TokenCreated(address token, string name, string symbol, uint256 supply, address creator);\n\n    function createToken(string memory name, string memory symbol, uint256 supply) external {\n        FactoryToken token = new FactoryToken(name, symbol, supply, msg.sender);\n        deployedTokens.push(address(token));\n        creatorTokens[msg.sender].push(address(token));\n        emit TokenCreated(address(token), name, symbol, supply, msg.sender);\n    }\n\n    function getDeployedTokens() external view returns (address[] memory) {\n        return deployedTokens;\n    }\n}`, version: '0.8.19', desc: 'Factory pattern for deploying ERC20 tokens' },
];

async function seed() {
  if (process.env.ALLOW_DESTRUCTIVE_SEED !== 'true') throw new Error('Set ALLOW_DESTRUCTIVE_SEED=true to run the destructive seed explicitly');
  if (!process.env.SEED_ADMIN_PASSWORD || process.env.SEED_ADMIN_PASSWORD.length < 12) throw new Error('SEED_ADMIN_PASSWORD must contain at least 12 characters');
  console.log('🌱 Seeding database...');

  // Clean existing data
  await prisma.auditHistory.deleteMany();
  await prisma.vulnerability.deleteMany();
  await prisma.auditReport.deleteMany();
  await prisma.smartContract.deleteMany();
  await prisma.project.deleteMany();
  await prisma.complianceTemplate.deleteMany();
  await prisma.user.deleteMany();

  // Create users
  const hashedPassword = await bcrypt.hash(process.env.SEED_ADMIN_PASSWORD, 12);
  const admin = await prisma.user.create({
    data: { email: 'admin@auditor.com', password: hashedPassword, firstName: 'Admin', lastName: 'User', role: 'ADMIN' },
  });
  const users = [admin];
  const roles: Array<'AUDITOR' | 'DEVELOPER' | 'VIEWER'> = ['AUDITOR', 'DEVELOPER', 'VIEWER', 'AUDITOR'];
  const names = [
    { first: 'Alice', last: 'Chen' }, { first: 'Bob', last: 'Smith' },
    { first: 'Carol', last: 'Johnson' }, { first: 'Dave', last: 'Williams' },
  ];
  for (let i = 0; i < 4; i++) {
    const u = await prisma.user.create({
      data: { email: `${names[i].first.toLowerCase()}@auditor.com`, password: hashedPassword, firstName: names[i].first, lastName: names[i].last, role: roles[i] },
    });
    users.push(u);
  }
  console.log(`  ✅ Created ${users.length} users`);

  // Create projects (15)
  const projectData = [
    { name: 'DeFi Yield Aggregator', desc: 'Automated yield optimization across multiple protocols', blockchain: 'Ethereum' },
    { name: 'NFT Marketplace v2', desc: 'Next-gen NFT trading platform with royalty enforcement', blockchain: 'Ethereum' },
    { name: 'Cross-Chain Bridge', desc: 'Secure bridge for token transfers between L1 and L2', blockchain: 'Polygon' },
    { name: 'DAO Governance Suite', desc: 'Complete governance framework for DAOs', blockchain: 'Ethereum' },
    { name: 'Staking Protocol', desc: 'Liquid staking derivatives platform', blockchain: 'Ethereum' },
    { name: 'DEX Aggregator', desc: 'Multi-DEX swap router for best price execution', blockchain: 'Arbitrum' },
    { name: 'Lending Protocol v3', desc: 'Overcollateralized lending and borrowing', blockchain: 'Ethereum' },
    { name: 'Token Launchpad', desc: 'Fair launch platform for new token projects', blockchain: 'BSC' },
    { name: 'Insurance Protocol', desc: 'Decentralized insurance for smart contract risks', blockchain: 'Ethereum' },
    { name: 'Perpetual DEX', desc: 'Perpetual futures decentralized exchange', blockchain: 'Arbitrum' },
    { name: 'Move DeFi Suite', desc: 'DeFi primitives built on Aptos', blockchain: 'Aptos' },
    { name: 'Gaming NFT Platform', desc: 'Play-to-earn gaming asset marketplace', blockchain: 'Sui' },
    { name: 'RWA Tokenization', desc: 'Real-world asset tokenization platform', blockchain: 'Ethereum' },
    { name: 'Privacy Protocol', desc: 'ZK-proof based private transactions', blockchain: 'Ethereum' },
    { name: 'Derivatives Vault', desc: 'Structured products and options vaults', blockchain: 'Optimism' },
  ];

  const projects = [];
  for (const p of projectData) {
    const project = await prisma.project.create({
      data: { name: p.name, description: p.desc, blockchain: p.blockchain, status: 'active', userId: users[Math.floor(Math.random() * users.length)].id },
    });
    projects.push(project);
  }
  console.log(`  ✅ Created ${projects.length} projects`);

  // Create contracts (18)
  const contracts = [];
  for (let i = 0; i < solidityContracts.length; i++) {
    const sc = solidityContracts[i];
    const contract = await prisma.smartContract.create({
      data: {
        name: sc.name, fileName: sc.fileName, sourceCode: sc.code,
        language: 'SOLIDITY', version: sc.version, description: sc.desc,
        projectId: projects[i % projects.length].id,
        userId: users[i % users.length].id,
      },
    });
    contracts.push(contract);
  }
  console.log(`  ✅ Created ${contracts.length} contracts`);

  // Create audit reports (16)
  const statuses: Array<'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED'> = ['COMPLETED', 'COMPLETED', 'COMPLETED', 'IN_PROGRESS', 'PENDING', 'COMPLETED', 'FAILED'];
  const auditReports = [];
  for (let i = 0; i < 16; i++) {
    const status = statuses[i % statuses.length];
    const report = await prisma.auditReport.create({
      data: {
        title: `Audit: ${contracts[i % contracts.length].name}`,
        contractId: contracts[i % contracts.length].id,
        userId: users[i % users.length].id,
        status,
        overallScore: status === 'COMPLETED' ? Math.floor(Math.random() * 40) + 60 : null,
        gasScore: status === 'COMPLETED' ? Math.floor(Math.random() * 30) + 70 : null,
        securityScore: status === 'COMPLETED' ? Math.floor(Math.random() * 50) + 50 : null,
        codeQualityScore: status === 'COMPLETED' ? Math.floor(Math.random() * 30) + 70 : null,
        complianceScore: status === 'COMPLETED' ? Math.floor(Math.random() * 40) + 60 : null,
        summary: status === 'COMPLETED' ? `Comprehensive audit of ${contracts[i % contracts.length].name} completed. Multiple findings identified and documented.` : null,
      },
    });
    auditReports.push(report);
  }
  console.log(`  ✅ Created ${auditReports.length} audit reports`);

  // Create vulnerabilities (20+)
  const vulnData = [
    { title: 'Reentrancy in withdraw()', severity: 'CRITICAL' as const, category: 'reentrancy', desc: 'State changes after external call allow reentrancy attack', rec: 'Use checks-effects-interactions pattern or ReentrancyGuard', isReentrancy: true },
    { title: 'Unchecked return value', severity: 'HIGH' as const, category: 'unchecked-return', desc: 'Return value of low-level call not checked', rec: 'Always check return values of external calls', isReentrancy: false },
    { title: 'Missing access control', severity: 'HIGH' as const, category: 'access-control', desc: 'Critical function lacks proper access control modifier', rec: 'Add onlyOwner or role-based access control', isReentrancy: false },
    { title: 'Integer overflow risk', severity: 'MEDIUM' as const, category: 'overflow', desc: 'Arithmetic operation may overflow in edge cases', rec: 'Use SafeMath or Solidity ^0.8.0 checked arithmetic', isReentrancy: false },
    { title: 'Front-running vulnerability', severity: 'HIGH' as const, category: 'front-running', desc: 'Transaction ordering dependency allows MEV extraction', rec: 'Implement commit-reveal scheme or use private mempool', isReentrancy: false },
    { title: 'Denial of Service via gas limit', severity: 'MEDIUM' as const, category: 'dos', desc: 'Unbounded loop may exceed block gas limit', rec: 'Implement pagination or batch processing', isReentrancy: false },
    { title: 'Centralization risk', severity: 'MEDIUM' as const, category: 'access-control', desc: 'Single admin key controls critical functionality', rec: 'Implement multi-sig or timelock', isReentrancy: false },
    { title: 'Floating pragma', severity: 'LOW' as const, category: 'other', desc: 'Compiler version not locked', rec: 'Lock pragma to specific version', isReentrancy: false },
    { title: 'Missing events', severity: 'LOW' as const, category: 'other', desc: 'State-changing functions do not emit events', rec: 'Add events for all state changes', isReentrancy: false },
    { title: 'Cross-function reentrancy', severity: 'CRITICAL' as const, category: 'reentrancy', desc: 'Multiple functions share state that can be exploited', rec: 'Apply mutex lock across all functions that share state', isReentrancy: true },
    { title: 'Timestamp dependence', severity: 'LOW' as const, category: 'logic-error', desc: 'Block timestamp used for critical logic', rec: 'Avoid using block.timestamp for time-sensitive operations', isReentrancy: false },
    { title: 'Unprotected selfdestruct', severity: 'CRITICAL' as const, category: 'access-control', desc: 'selfdestruct callable by unauthorized users', rec: 'Add strict access control or remove selfdestruct', isReentrancy: false },
    { title: 'Flash loan attack vector', severity: 'HIGH' as const, category: 'logic-error', desc: 'Price oracle manipulable via flash loans', rec: 'Use TWAP oracle or Chainlink price feeds', isReentrancy: false },
    { title: 'Unsafe delegatecall', severity: 'CRITICAL' as const, category: 'other', desc: 'delegatecall to user-supplied address', rec: 'Validate target address against whitelist', isReentrancy: false },
    { title: 'Missing zero-address check', severity: 'LOW' as const, category: 'other', desc: 'Constructor does not validate against zero address', rec: 'Add require(addr != address(0)) checks', isReentrancy: false },
    { title: 'Storage collision', severity: 'HIGH' as const, category: 'logic-error', desc: 'Proxy storage layout conflicts with implementation', rec: 'Use EIP-1967 storage slots', isReentrancy: false },
    { title: 'Signature replay attack', severity: 'HIGH' as const, category: 'other', desc: 'Signatures can be replayed across chains or transactions', rec: 'Include chain ID and nonce in signed message', isReentrancy: false },
    { title: 'Read-only reentrancy', severity: 'MEDIUM' as const, category: 'reentrancy', desc: 'View function reads stale state during reentrancy', rec: 'Use reentrancy locks on view functions that read critical state', isReentrancy: true },
    { title: 'Sandwich attack vulnerability', severity: 'MEDIUM' as const, category: 'front-running', desc: 'Swap function vulnerable to sandwich attacks', rec: 'Add slippage protection and deadline parameters', isReentrancy: false },
    { title: 'Insufficient randomness', severity: 'MEDIUM' as const, category: 'logic-error', desc: 'On-chain randomness is predictable', rec: 'Use Chainlink VRF for secure randomness', isReentrancy: false },
  ];

  for (let i = 0; i < vulnData.length; i++) {
    const v = vulnData[i];
    await prisma.vulnerability.create({
      data: {
        contractId: contracts[i % contracts.length].id,
        auditReportId: auditReports[i % auditReports.length].id,
        title: v.title, description: v.desc, severity: v.severity, category: v.category,
        recommendation: v.rec, isReentrancy: v.isReentrancy, status: i % 4 === 0 ? 'fixed' : 'open',
      },
    });
  }
  console.log(`  ✅ Created ${vulnData.length} vulnerabilities`);

  // Create compliance templates (15)
  const templateData = [
    { name: 'ERC20 Standard', standard: 'ERC20' as const, desc: 'Full ERC20 token standard compliance', rules: [{ rule: 'totalSupply()', required: true }, { rule: 'balanceOf(address)', required: true }, { rule: 'transfer(address,uint256)', required: true }, { rule: 'approve(address,uint256)', required: true }, { rule: 'transferFrom(address,address,uint256)', required: true }, { rule: 'allowance(address,address)', required: true }] },
    { name: 'ERC20 with Extensions', standard: 'ERC20' as const, desc: 'ERC20 with mint, burn, and pause', rules: [{ rule: 'mint(address,uint256)', required: false }, { rule: 'burn(uint256)', required: false }, { rule: 'pause()', required: false }, { rule: 'unpause()', required: false }] },
    { name: 'ERC721 Standard', standard: 'ERC721' as const, desc: 'Full ERC721 NFT standard', rules: [{ rule: 'balanceOf(address)', required: true }, { rule: 'ownerOf(uint256)', required: true }, { rule: 'safeTransferFrom(address,address,uint256)', required: true }, { rule: 'approve(address,uint256)', required: true }, { rule: 'setApprovalForAll(address,bool)', required: true }] },
    { name: 'ERC721 Enumerable', standard: 'ERC721' as const, desc: 'ERC721 with enumeration extension', rules: [{ rule: 'totalSupply()', required: true }, { rule: 'tokenByIndex(uint256)', required: true }, { rule: 'tokenOfOwnerByIndex(address,uint256)', required: true }] },
    { name: 'ERC721 Metadata', standard: 'ERC721' as const, desc: 'ERC721 with metadata extension', rules: [{ rule: 'name()', required: true }, { rule: 'symbol()', required: true }, { rule: 'tokenURI(uint256)', required: true }] },
    { name: 'ERC1155 Standard', standard: 'ERC1155' as const, desc: 'Multi-token standard compliance', rules: [{ rule: 'balanceOf(address,uint256)', required: true }, { rule: 'balanceOfBatch(address[],uint256[])', required: true }, { rule: 'safeTransferFrom(address,address,uint256,uint256,bytes)', required: true }, { rule: 'safeBatchTransferFrom(address,address,uint256[],uint256[],bytes)', required: true }] },
    { name: 'ERC777 Standard', standard: 'ERC777' as const, desc: 'Advanced token standard with hooks', rules: [{ rule: 'send(address,uint256,bytes)', required: true }, { rule: 'operatorSend(address,address,uint256,bytes,bytes)', required: true }, { rule: 'burn(uint256,bytes)', required: true }] },
    { name: 'ERC4626 Vault', standard: 'ERC4626' as const, desc: 'Tokenized vault standard', rules: [{ rule: 'asset()', required: true }, { rule: 'totalAssets()', required: true }, { rule: 'deposit(uint256,address)', required: true }, { rule: 'withdraw(uint256,address,address)', required: true }, { rule: 'redeem(uint256,address,address)', required: true }] },
    { name: 'DeFi Safety Checklist', standard: 'CUSTOM' as const, desc: 'General DeFi protocol safety requirements', rules: [{ rule: 'Emergency pause mechanism', required: true }, { rule: 'Timelock on admin functions', required: true }, { rule: 'Multi-sig admin', required: true }, { rule: 'Oracle manipulation protection', required: true }] },
    { name: 'Bridge Security Template', standard: 'CUSTOM' as const, desc: 'Cross-chain bridge security requirements', rules: [{ rule: 'Multi-validator consensus', required: true }, { rule: 'Rate limiting', required: true }, { rule: 'Emergency shutdown', required: true }, { rule: 'Message verification', required: true }] },
    { name: 'DAO Governance Template', standard: 'CUSTOM' as const, desc: 'DAO governance best practices', rules: [{ rule: 'Proposal threshold', required: true }, { rule: 'Voting delay', required: true }, { rule: 'Quorum requirement', required: true }, { rule: 'Timelock execution', required: true }] },
    { name: 'NFT Royalty Standard', standard: 'CUSTOM' as const, desc: 'EIP-2981 royalty compliance', rules: [{ rule: 'royaltyInfo(uint256,uint256)', required: true }, { rule: 'supportsInterface(bytes4)', required: true }] },
    { name: 'Upgradeable Contract Template', standard: 'CUSTOM' as const, desc: 'Proxy upgrade safety requirements', rules: [{ rule: 'No constructor usage', required: true }, { rule: 'Initializer pattern', required: true }, { rule: 'Storage gap reservation', required: true }, { rule: 'Admin access control', required: true }] },
    { name: 'Staking Protocol Template', standard: 'CUSTOM' as const, desc: 'Staking protocol requirements', rules: [{ rule: 'Reward calculation accuracy', required: true }, { rule: 'Withdrawal delay', required: false }, { rule: 'Slashing conditions', required: false }, { rule: 'Emergency unstake', required: true }] },
    { name: 'AMM DEX Template', standard: 'CUSTOM' as const, desc: 'AMM DEX security requirements', rules: [{ rule: 'Slippage protection', required: true }, { rule: 'Deadline parameter', required: true }, { rule: 'Minimum liquidity lock', required: true }, { rule: 'Flash loan resistance', required: true }] },
  ];

  for (const t of templateData) {
    await prisma.complianceTemplate.create({
      data: { name: t.name, standard: t.standard, description: t.desc, rules: t.rules, version: '1.0', isActive: true },
    });
  }
  console.log(`  ✅ Created ${templateData.length} compliance templates`);

  // Create audit history (25+)
  const actions = ['vulnerability_scan', 'gas_optimization', 'compliance_check', 'test_generation', 'code_quality', 'reentrancy_detection'];
  for (let i = 0; i < 25; i++) {
    const action = actions[i % actions.length];
    await prisma.auditHistory.create({
      data: {
        action,
        contractId: contracts[i % contracts.length].id,
        userId: users[i % users.length].id,
        input: { language: 'Solidity', codeLength: contracts[i % contracts.length].sourceCode.length },
        result: { summary: `${action.replace('_', ' ')} completed for ${contracts[i % contracts.length].name}`, score: Math.floor(Math.random() * 40) + 60 },
        status: 'COMPLETED',
        duration: Math.floor(Math.random() * 5000) + 1000,
      },
    });
  }
  console.log(`  ✅ Created 25 audit history entries`);

  console.log('\n🎉 Database seeded successfully!');
  console.log(`\n📧 Login: admin@auditor.com / password`);
}

seed().catch(console.error).finally(() => prisma.$disconnect());
